with Humanize.Tests.Datetimes;
with Humanize.Tests.Durations;
with Humanize.Tests.Bytes;
with Humanize.Tests.Colors;
with Humanize.Tests.Numbers;
with Humanize.Tests.Units;
with Humanize.Tests.Rendering;
with Humanize.Tests.Bounded;
with Humanize.Tests.Architecture;
with Humanize.Tests.Strings;
with Humanize.Tests.Values;
with Humanize.Tests.Endpoints;
with Humanize.Tests.Resources;
with Humanize.Tests.Versions;
with Humanize.Tests.Geo;
with Humanize.Tests.Markup;
with Humanize.Tests.Secrets;
with Humanize.Tests.Schema;
with Humanize.Tests.Diagnostics;
with Humanize.Tests.Thresholds;
with Humanize.Tests.Workflows;
with Humanize.Tests.Changes;
with Humanize.Tests.Tables;
with Humanize.Tests.Forms;
with Humanize.Tests.Navigation;
with Humanize.Tests.Badges;
with Humanize.Tests.Notifications;
with Humanize.Tests.Search;
with Humanize.Tests.Comments;
with Humanize.Tests.Tasks;
with Humanize.Tests.Attachments;
with Humanize.Tests.Events;
with Humanize.Tests.Payments;
with Humanize.Tests.System_Status;
with Humanize.Tests.Domain_Gaps;
with Humanize.Tests.Parsing;
with Humanize.Tests.Compatibility;
with AUnit.Test_Cases;

package body Humanize.Tests.Suite is

   function Suite return AUnit.Test_Suites.Access_Test_Suite is
      Result : constant AUnit.Test_Suites.Access_Test_Suite :=
        new AUnit.Test_Suites.Test_Suite;
   begin
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Datetimes.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Durations.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Bytes.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Colors.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Numbers.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Units.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Rendering.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Bounded.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Architecture.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Strings.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Values.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Endpoints.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Resources.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Versions.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Geo.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Markup.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Secrets.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Schema.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Diagnostics.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Thresholds.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Workflows.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Changes.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Tables.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Forms.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Navigation.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Badges.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Notifications.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Search.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Comments.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Tasks.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Attachments.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Events.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Payments.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.System_Status.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Domain_Gaps.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Parsing.Test_Case));
      Result.Add_Test (AUnit.Test_Cases.Test_Case_Access'(new Humanize.Tests.Compatibility.Test_Case));
      return Result;
   end Suite;

end Humanize.Tests.Suite;
